name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Generate test.env file
        run: echo "OPENIA_KEY=${{ secrets.OPENIA_KEY }}" >> test.env && echo "OPENIA_URL=${{ secrets.OPENIA_URL }}" >> test.env

      - name: Delay
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Run tests
        run: vendor/bin/phpunit
